### ISSUE TITLE
Issue Test 2

### ISSUE THREAD

**Issue by bultas** [catchcake/test#6]

**Comment by bultas** [comment]
zkus si to svalne uzavrit a pozorovat ten project board

https://github.com/orgs/catchcake/projects/1?fullscreen=true

- problemy jsou predevsim v tom, ze github neumi otevirat empty pull request, takze workaround je, ze se udela empty commit, kde je napriklad informace co se zavira za listecek:

`git commit --allow-empty -m "fix #6"`

**Comment by bultas** [comment]
na co nezapomentou, je predevsim oznacit pull request, ze ma byt v projektu

**Comment by s-m-i-t-a** [comment]
Hmm, to zni jako to prave chtene UX, co clovek jeste nikdy nezazil. Sry, za sarkasmus. Kdyz to vidim, tak bych radsi presel na gitlab, protoze tam lze z issue rovnou vytvorit vetev, tedy otevrit praci nebo rovnou PR (coz znamena, ze se ukol stal *In Progress*). GitHub dle meho by mel celou nastavbu jmenem *Projects* zahodit, protoze mne pripada, ze musim v tom najit skryty smysl, abych to mohl pouzivat nebo napsat opravdu dobrou dokumntaci pro hloupe, co nevidi pridanou hodnotu. Pokud to chces pouzivat ok, ale ja si pak musim sehnat neco na konzoli, kde mne to dovoli mit nejaky intuitivnejsi ovladani.
